pipeline {
   agent any

   stages {
      stage('Hello') {
         steps {
           
            git 'https://github.com/kalikichandu/DevOps-for-ML.git'
            
            dir('DevOps-for-ML') {
                // some block
               pwd()
               fileExists '/Dockerfile'
            }
         }
      }
   }
}
